//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class blogWebsiteDBEntities7 : DbContext
    {
        public blogWebsiteDBEntities7()
            : base("name=blogWebsiteDBEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Comment> tb_Comment { get; set; }
        public virtual DbSet<tb_fens> tb_fens { get; set; }
        public virtual DbSet<tb_GoodFriend> tb_GoodFriend { get; set; }
        public virtual DbSet<tb_Grouping> tb_Grouping { get; set; }
        public virtual DbSet<tb_MicroBlog> tb_MicroBlog { get; set; }
        public virtual DbSet<tb_Pinglun> tb_Pinglun { get; set; }
        public virtual DbSet<tb_Search> tb_Search { get; set; }
        public virtual DbSet<tb_UserInfo> tb_UserInfo { get; set; }
    }
}
