//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    public partial class Search
    {
        /// <summary>
        /// lblKw 控件。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblKw;

        /// <summary>
        /// lblCount 控件。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCount;

        /// <summary>
        /// rptResult 控件。
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptResult;

        /// <summary>
        /// lblEmpty 控件。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmpty;
    }
}
