//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Comment
    {
        public int ID { get; set; }
        public int CommentatorUserID { get; set; }
        public int BeCommentatorUserID { get; set; }
        public string Content_text { get; set; }
        public string Content_img { get; set; }
        public string Content_video { get; set; }
        public string Content__sound { get; set; }
        public Nullable<System.DateTime> CommentTime { get; set; }
    }
}
