//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fens
    {
        public int id { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public string url { get; set; }
        public string num { get; set; }
        public int userID { get; set; }
        public string count { get; set; }
        public string address { get; set; }
    
        public virtual tb_UserInfo tb_UserInfo { get; set; }
    }
}
