//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GoodFriend
    {
        public int ID { get; set; }
        public Nullable<int> MyUserID { get; set; }
        public Nullable<int> FollowUserID { get; set; }
        public Nullable<int> FansUserID { get; set; }
        public string FriendRemarks { get; set; }
        public Nullable<System.DateTime> Establish { get; set; }
        public Nullable<int> AitemeUserID { get; set; }
    
        public virtual tb_UserInfo tb_UserInfo { get; set; }
    }
}
