//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MicroBlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_MicroBlog()
        {
            this.tb_Pinglun = new HashSet<tb_Pinglun>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Content_text { get; set; }
        public string Content_img { get; set; }
        public string Content_video { get; set; }
        public string Content__sound { get; set; }
        public Nullable<int> Points_number { get; set; }
        public string Place { get; set; }
        public Nullable<int> Cansee_states { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
    
        public virtual tb_UserInfo tb_UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Pinglun> tb_Pinglun { get; set; }
    }
}
