//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_UserInfo()
        {
            this.tb_fens = new HashSet<tb_fens>();
            this.tb_GoodFriend = new HashSet<tb_GoodFriend>();
            this.tb_MicroBlog = new HashSet<tb_MicroBlog>();
            this.tb_Pinglun = new HashSet<tb_Pinglun>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> UserSex { get; set; }
        public Nullable<int> UserFansNum { get; set; }
        public Nullable<System.DateTime> UserBirthday { get; set; }
        public string UserRegion { get; set; }
        public string UserHeadPortrait { get; set; }
        public string UserAutograph { get; set; }
        public Nullable<int> States { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public string UserYM { get; set; }
        public string UserGQ { get; set; }
        public string UserJX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fens> tb_fens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_GoodFriend> tb_GoodFriend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MicroBlog> tb_MicroBlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Pinglun> tb_Pinglun { get; set; }
    }
}
